import { DataTypes, Transaction } from "sequelize";
import { z } from "zod";

import { sequelizeCfg } from "./postgresDB";

export const LoginTablePgModel = sequelizeCfg.define(
  "login",
  {
    loginid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    userid: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    email: {
      type: DataTypes.STRING(100),
      allowNull: false,
      unique: true,
    },
    hash: {
      type: DataTypes.STRING(100),
      allowNull: false,
    },
    isdeleted: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: false,
    },
    refresh_token: {
      type: DataTypes.TEXT,
      allowNull: true,
      defaultValue: false,
    },
  },
  {
    timestamps: false,
  }
);

//=========================================================================================

export const zodLoginTableType = z.object({
  //some elements are optional because it's already generated by system
  loginid: z.number().optional(),
  userid: z.number(),
  email: z.string().max(100).email(),
  hash: z.string().max(100),
  isdeleted: z.boolean().optional(),
  refresh_token: z.string().optional(),
});

export type LoginTableType = z.infer<typeof zodLoginTableType>;

export async function createNewLogin(
  data: LoginTableType,
  t: Transaction | null
) {
  return await LoginTablePgModel.create(data, { transaction: t })
    .then((data) => {
      return data.dataValues as unknown as LoginTableType;
    })
    .catch((error) => {
      throw new Error(
        "[DB - Login]: Unable to create new login data, email must be unique"
      );
    });
}

export async function getOneLoginData(email: string) {
  return await LoginTablePgModel.findOne({
    where: { email, isdeleted: false },
    raw: true,
  }).then((data: unknown) => {
    return data as LoginTableType;
  });
}

//=========================================================================================

type UpdateLoginInput = {
  refresh_token?: string | null;
  isdeleted?: boolean;
};

export async function updateLoginData(
  data: UpdateLoginInput,
  email: string,
  t?: Transaction | null
) {
  return await LoginTablePgModel.update(data, {
    where: { email },
    transaction: t,
  })
    .then((result) => {
      return true;
    })
    .catch((error) => {
      console.error(error);
      throw new Error(
        "[DB - Login]: unable to update login database, try again later"
      );
    });
}

//=========================================================================================
